stages:
  - lint_n_vet_n_test
  - containerize

linting, vetting and running the test suite:
  stage: lint_n_vet_n_test
  image: golang:latest
  script:
    - ln -s $CI_PROJECT_DIR /go/src/carsten-coffee-api
    - cd /go/src/carsten-coffee-api
    - ./run-tests.sh

containerizing:
  stage: containerize
  image: docker:18
  script:
    - echo "$DOCKER_BUILDER_CERT_PEM" > /root/cert.pem
    - echo "$DOCKER_BUILDER_KEY_PEM" > /root/key.pem
    - echo "$DOCKER_BUILDER_CA_PEM" > /root/ca.pem
    - export DOCKER_TLS_VERIFY="1"
    - export DOCKER_HOST="$DOCKER_BUILDER_HOST"
    - export DOCKER_CERT_PATH="/root"
    - docker build -t carsten-coffee-api:latest .

