name: CI Testsuite

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18'
        check-latest: true
        cache: true

    - name: Install golint
      run: sudo apt-get install -y golint

    - name: Install dependencies
      run: make prep

    - name: Run Lint
      run: make lint

    - name: Run testsuite
      run: make test-ci

    - uses: actions/upload-artifact@v3
      with:
        name: JUnit
        path: junit.xml
